# This is supposed to be used together with `--build-upon-default-config` CLI option.
# Meaning that all the defaults would be respected, except that we don't want to exclude
# `DetektProgressListener`. Therefore, `exclude` is set to an empty array.
processors:
  active: true
  exclude: []