name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: "-Dorg.gradle.console=plain -Dorg.gradle.caching=true -Dsonar.gradle.skipCompile=true"

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/gradle-action
      - run: ./gradlew classes
      - name: Install Lighthouse CI
        run: npm install
      - name: Run Lighthouse CI
        run: npx lhci autorun
        env:
          PROJECT_TOKEN: ${{ vars.LHCI_PROJECT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
          BASIC_AUTH_USERNAME: ${{ secrets.LHCI_BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.LHCI_BASIC_AUTH_PASSWORD }}