name: "Validate External Links"

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "opened", "synchronize", "reopened" ]

jobs:
  validate-external-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: '--verbose --no-progress --exclude-loopback --exclude-path node_modules **/*.md'
          jobSummary: true
          format: markdown
          fail: true
